version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: am-wireguard_server_1
      APP_PORT: 80

  server:
    image: ngoduykhanh/wireguard-ui:latest
    hostname: "${DEVICE_HOSTNAME}"
    cap_add:
      - NET_ADMIN
    environment:
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=admin
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=false
      - WGUI_MANAGE_RESTART=false
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ${UMBREL_ROOT}/data/storage/wireguard/db:/app/db
      - ${UMBREL_ROOT}/data/storage/wireguard:/etc/wireguard
    ports:
      - 51820:51820